POST http://localhost:3000/user/create
content-type: application/json

{
  "name": "kaua",
  "email": "kaua@gmail.com",
  "password": "123456"
}

###
GET http://localhost:3000/user/login
content-type: application/json

{
  "email": "kaua@gmail.com",
  "password": "123456"
}

###
PATCH http://localhost:3000/user/update/2
content-type: application/json

{
  "name": "Kauã"
}